"""password column

Revision ID: 141a6bd7701a
Revises: fb2ca083e154
Create Date: 2021-11-02 14:31:22.431074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141a6bd7701a'
down_revision = 'fb2ca083e154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
